const BookData = [
    {
      id: 1,
      title: "The Great Gatsby",
      author: "F. Scott Fitzgerald",
      category: "Classics",
      price: 12.99,
      description: "A novel set in the Roaring Twenties, exploring themes of wealth, love, and the American Dream.",
      image: "https://res.cloudinary.com/drphumgcb/image/upload/f_auto,q_auto/v1724116048/gatsby_whjsra.jpg",
      rating: 4.5,
    },
    {
      id: 2,
      title: "1984",
      author: "George Orwell",
      category: "Classics",
      price: 10.99,
      description: "A dystopian novel that delves into the dangers of totalitarianism and extreme political ideology.",
      image: "https://res.cloudinary.com/drphumgcb/image/upload/f_auto,q_auto/v1724116171/1984_odbwnt.jpg",
      rating: 4.8,
    },
    {
      id: 3,
      title: "The Alchemist",
      author: "Paulo Coelho",
      category: "Fiction",
      price: 14.99,
      description: "A philosophical novel that follows a shepherd's journey to find treasure and fulfill his destiny.",
      image: "https://res.cloudinary.com/drphumgcb/image/upload/f_auto,q_auto/v1724116249/alchemist_tfrpji.jpg",
      rating: 4.6,
    },
    {
      id: 4,
      title: "Becoming",
      author: "Michelle Obama",
      category: "Non-Fiction",
      price: 19.99,
      description: "An intimate and inspiring memoir by the former First Lady of the United States.",
      image: "https://res.cloudinary.com/drphumgcb/image/upload/f_auto,q_auto/v1723851557/becoming_h3xzjl.jpg",
      rating: 4.9,
    },
    {
      id: 5,
      title: "The Silent Patient",
      author: "Alex Michaelides",
      category: "Mystery & Thriller",
      price: 15.99,
      description: "A psychological thriller about a woman who shoots her husband and then never speaks again.",
      image: "https://res.cloudinary.com/drphumgcb/image/upload/c_fill,w_300,h_450/q_auto,f_auto/v1723850875/patient_yqjrt8.jpg",
      rating: 4.7,
    },
    {
      id: 6,
      title: "Educated",
      author: "Tara Westover",
      category: "Non-fiction",
      price: 18.99,
      description: "A memoir about a woman who grew up in a strict and abusive household in rural Idaho but eventually escaped to learn about the wider world through education.",
      image: "https://res.cloudinary.com/drphumgcb/image/upload/f_auto,q_auto/v1723852531/educated_mbjgek.jpg",
      rating: 4.8,
    },
    {
      id: 7,
      title: "Harry Potter and the Sorcerer's Stone",
      author: "J.K. Rowling",
      category: "Teen",
      price: 22.99,
      description: "The first book in the Harry Potter series, where a young boy discovers he is a wizard and attends Hogwarts School of Witchcraft and Wizardry.",
      image: "https://res.cloudinary.com/drphumgcb/image/upload/f_auto,q_auto/v1724115763/harry_qmbeo6.jpg",
      rating: 4.9,
    },
    {
      id: 8,
      title: "Goodnight Moon",
      author: "Margaret Wise Brown",
      category: "Children Books",
      price: 8.99,
      description: "A beloved bedtime story that has been soothing children to sleep for generations.",
      image: "https://res.cloudinary.com/drphumgcb/image/upload/f_auto,q_auto/v1724115877/moonlight_ouiy9w.jpg",
      rating: 4.7,
    },
    {
      id: 9,
      title: "The Lean Startup",
      author: "Eric Ries",
      category: "Business & Economics",
      price: 16.99,
      description: "A guide to efficient business practices and lean product development.",
      image: "https://res.cloudinary.com/drphumgcb/image/upload/f_auto,q_auto/v1724116343/lean_idnoks.png",
      rating: 4.5,
    },
    {
      id: 10,
      title: "Atomic Habits",
      author: "James Clear",
      category: "Health and Wellness",
      price: 14.99,
      description: "A book that explores how small changes can lead to significant improvements in one's life.",
      image: "https://res.cloudinary.com/drphumgcb/image/upload/f_auto,q_auto/v1723851462/1696425885734_rlc7xh.jpg",
      rating: 4.8,
    },
    {
        id: 11,
        title: "The Body Keeps the Score",
        author: "Bessel van der Kolk",
        category: "Health and Wellness",
        price: 14.99,
        description: "A groundbreaking book on trauma and its impact on the body, mind, and spirit.",
        image: "https://res.cloudinary.com/drphumgcb/image/upload/f_auto,q_auto/v1724116424/score_grvqm9.jpg",
        rating: 4.8,
      },
      {
        id: 12,
        title: "Rich Dad Poor Dad",
        author: "Robert T. Kiyosaki",
        category: "Business & Economics",
        price: 9.99,
        description: "A personal finance classic on the mindset of wealth building.",
        image: "https://res.cloudinary.com/drphumgcb/image/upload/f_auto,q_auto/v1724116593/rdpd_w9jcoi.jpg",
        rating: 4.7,
      },
  ];

  export default BookData;
  